server.compression.enabled=false
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,image/jpeg
server.compression.min-response-size=2048

skipStoragePolicy = true
skipAccessPolicy = true
storagePolicy.storeType = 'FILE_STORE'
storagePolicy.maxSize = 31457280
storagePolicy.dirPath = /Users/hemantm/work/tmp

